### ISSUE TITLE
Research go 

### ISSUE THREAD

**Issue by zhulia960821** [bobheadxi/calories#1]
Become familiar with syntax, structure, etc

**Comment by bobheadxi** [comment]
Some good resources:
- [Getting Started Documentation](https://golang.org/doc/code.html)
- [Go cheatsheet](http://www.newthinktank.com/2015/02/go-programming-tutorial/)
- [Consuming REST APIs in Go](https://medium.com/@IndianGuru/consuming-json-apis-with-go-d711efc1dcf9)
- [Go and Postgres](https://github.com/lib/pq)
- [Go Package Manager](https://github.com/Masterminds/glide)
- [Go and Heroku](https://github.com/heroku/go-getting-started)

Examples:
- [Facebook Messenger interactions in Go](https://github.com/abhinavdahiya/go-messenger-bot/blob/master/messenger.go) - we won't use this wrapper, but use it to guide building our own stuff (another one [here](https://github.com/kkdai/FBBotTemplate))
- [Go Slack Bot](https://github.com/ubclaunchpad/rocket)

**Comment by bobheadxi** [comment]
See the [wiki](https://github.com/bobheadxi/calories/wiki/Golang-Resources)!
